Add test for findClosestParentPath to check for figtree regression
I inadvertently 'upgraded' to coryb/figtree v1.0.0, and it caused an
error in findCLosestParentPath, due to figtree.FindParentPaths having
a different function signature in v1.0.0

No idea why a regular compile isn't picking this up - but when
explicitly testing like this, we get the error detailed in #277:

```
Mikes-MBP:jira mike$ go test ./...
?       github.com/go-jira/jira [no test files]
jiracli/util.go:29:34: too many arguments in call to figtree.FindParentPaths
        have (string, string, string)
        want (string)
jiracli/util.go:29:34: too many arguments in call to figtree.FindParentPaths
        have (string, string, string)
        want (string)
FAIL    github.com/go-jira/jira/jiracli [build failed]
ok      github.com/go-jira/jira/jiradata        (cached)
Mikes-MBP:jira mike$
```